title = "Boil-Off Gas Compressor Operations"

content = """
BOG compressors handle vapor generated by heat ingress and unloading displacement. The Board Operator manages suction pressure by staging compressor cylinders. Knock-out drums upstream must be drained regularly to prevent liquid carryover.
*   Suction Pressure: Maintain compressor suction at 12 kPag minimum.
*   Discharge Pressure: Compress gas to 65 barg for send-out mixing.
*   Vibration Limit: Shutdown if vibration exceeds 12 mm/s RMS on bearing housing.
*   Lube Oil: Temperature maintained at 45°C +/- 5°C.
*   Capacity Control: Slide valves adjust capacity from 25% to 100% in steps.
"""  # noqa: E501

version = "0.0.1"
