title = "Extreme Ultraviolet (EUV) Lithography"

content = """
Extreme Ultraviolet (EUV) lithography is the cutting-edge technology used for 
sub-7nm semiconductor nodes. It uses a wavelength of 13.5nm, which is absorbed 
by almost all materials, including air and glass. This necessitates a vacuum 
environment and reflective optics (mirrors) instead of refractive lenses.

**EUV Light Source:**
The light is generated by hitting droplets of molten tin with a high-power CO2 
laser. This creates a plasma that emits 13.5nm radiation. The light is then 
collected and directed through a series of multilayer mirrors (Mo/Si) to the 
photomask and finally to the wafer.

**Reflective Optics:**
Since EUV is absorbed by glass, traditional lenses cannot be used. Instead, 
Bragg reflectors consisting of alternating layers of Molybdenum and Silicon 
are used. These mirrors must be manufactured with atomic-scale precision to 
minimize scattering and maintain wavefront quality.

**Stochastic Effects:**
Due to the high energy of EUV photons, fewer photons are used for each exposure 
compared to DUV. This leads to "photon shot noise" or stochastic effects, 
which cause random variations in pattern edges (Line Edge Roughness) and 
critical dimensions. Managing stochastics is a primary challenge in EUV 
lithography.
"""

version = "0.0.1"
