title = "Real-Time Fraud Alert System"

content = """
- Alerts are generated by rules (e.g., "New device + amount >$500") and ML model (gradient boosting, score 0-100).
- Priority levels: Critical (score >85), High (70-85), Medium (50-69), Low (<50). Critical alerts must be reviewed within 5 minutes.
- Alert dashboard shows: transaction ID, amount, timestamp, risk score, triggered rules, device fingerprint, IP geolocation.
- Analysts can snooze alerts (max 30 min) if waiting for additional data.
"""  # noqa: E501

version = "0.0.1"
