title = "Production Floor Roles and Responsibilities"

content = """
A clear role structure on the Ridgecrest Metalworks production floor ensures accountability, minimizes
confusion during critical operations, and supports safe handovers between shifts. Every person working on
the floor has a defined scope of authority and responsibility.

Production Operators are the core execution workforce. They operate specific machines or process stations,
follow work orders and traveler documents, perform in-process quality checks, and report deviations to their
cell lead. Operators are required to complete machine-specific qualification training before working
unsupervised on any equipment.

Cell Leads are senior operators who provide front-line technical guidance within a production cell. They
manage daily task sequencing, coordinate with the shift supervisor on priorities, assist with troubleshooting
minor equipment issues, and verify that first-article inspections are completed correctly. Cell leads do not
have formal managerial authority but serve as the first point of escalation for operators.

Shift Supervisors hold operational authority for all production activity during their assigned shift. They
are responsible for safety compliance, production rate attainment, shift handover documentation, and
real-time escalation of quality holds or equipment failures. A shift supervisor must be present on the floor
at all times during active production.

Process Engineers support the floor by maintaining work instructions, addressing non-conformances, and
driving process improvement initiatives. They are not production supervisors but may temporarily direct
operators during process qualification events or root cause investigations.

Quality Technicians perform dimensional inspections, in-process audits, first-article inspections, and
non-destructive testing. They have the authority to place parts or lots on quality hold and must be
consulted before any non-conforming material is dispositioned.

Maintenance Technicians respond to equipment breakdowns, perform preventive maintenance, and complete
work orders generated by the production team. Operators must not attempt repairs beyond their specific
authorization; all equipment issues requiring intervention beyond operator-level adjustment must be
reported via the maintenance request system.

The Facility Safety Officer oversees all safety programs, conducts audits, investigates incidents, and
maintains compliance documentation. The Safety Officer has stop-work authority that supersedes all
production priorities when an imminent hazard is identified.
"""

version = "0.0.1"
