title = "Hydraulic System Maintenance and Fluid Care"

content = """
Hydraulic systems at Ridgecrest Metalworks — press brakes, hydraulic presses, clamping systems, and lifting equipment — convert fluid pressure into mechanical force. Hydraulic system reliability depends heavily on fluid cleanliness, correct fluid type, and maintenance of seals, filters, and actuators.

Hydraulic fluid contamination is the leading cause of hydraulic system failures. Particulate contamination (metal wear particles, ingressed dirt, and degraded fluid) causes abrasive wear in precision components (servo valves, variable displacement pumps, motors) that have clearances of 5–20 µm. Water contamination reduces lubricity, promotes corrosion, and degrades fluid additives. Air entrainment causes cavitation, spongy cylinder response, and pump damage.

Fluid cleanliness management:
- All new fluid must be filtered before introduction into the system; never add fluid directly from a drum without filtration
- Reservoir breathers (desiccant breathers preferred) prevent moisture and particle ingress
- Return line filters (10 µm absolute or finer) remove particles generated by actuator and valve wear during operation
- High-pressure filters protect servo valves in precision systems (3–6 µm absolute)
- Fluid cleanliness is measured using an automatic particle counter (ISO 4406:2021) on oil samples taken from the reservoir. Target cleanliness is specified in the machine documentation.

Fluid condition monitoring: Oil samples are drawn from the running system every 500–1000 hours or semi-annually. Laboratory analysis measures viscosity (should be within ±10–15 % of nominal), acid number (rising acid number indicates oxidation), water content (< 0.05 % for standard systems), and elemental analysis for wear metals (iron, copper, chromium indicate component wear).

Seal inspection and replacement: External cylinder seal leaks are visible; internal bypass leakage causes cylinder drift and loss of holding force. Cylinder seal kits are replaced on a time interval or when leakage is observed. Contaminated or overheated fluid accelerates seal degradation.

Filter service: Filter elements are replaced on a time interval and when the differential pressure indicator (bypass indicator) signals that the element is approaching bypass pressure. Used elements should be inspected for abnormal debris before disposal.

Hydraulic fluid is hazardous waste when spent. It must be collected by a licensed waste oil contractor. Mixing of incompatible fluid types (mineral oil and fire-resistant phosphate ester, for example) makes the resulting mixture non-recyclable and potentially hazardous; fluid types must not be mixed.
"""

version = "0.0.1"
