title = "Pneumatic System Maintenance and Air Quality"

content = """
Pneumatic systems power air cylinders, pneumatic tools, clamping devices, and blow-off systems throughout the Ridgecrest Metalworks facility. Compressed air is generated by rotary screw compressors, treated for water and oil contamination, and distributed through an aluminum or steel ring main at typically 7–8 bar (100–115 psi) operating pressure.

Compressed air quality requirements vary by application:
- General shop air (blow-off, pneumatic tools): ISO 8573-1 Class 5 or better (particulate ≤ 40 µm, pressure dewpoint ≤ +7 °C, oil content ≤ 25 mg/m³)
- Instrument and control air: ISO 8573-1 Class 2 or 3 (pressure dewpoint ≤ −20 °C, oil ≤ 1 mg/m³, particles ≤ 1 µm for Class 2)
- Painting and coating air: Oil-free (Class 1 oil content, ≤ 0.01 mg/m³) to prevent fish-eye and adhesion failures in coatings

Compressor maintenance:
- Air/oil separator element: Replace per manufacturer interval (typically 4000 hours or annually). A degraded separator allows oil carryover into the airline, contaminating downstream processes.
- Intake filter: Replace annually or when differential pressure exceeds 25 mbar. Blocked intake filter starves the compressor, causing overheating and elevated outlet temperature.
- Compressor oil: Change per oil analysis or annually. Degraded oil increases wear on rotors and bearings.
- Cooling fins: Clean annually to maintain heat rejection capacity. Blocked cooling causes high outlet temperature and thermal shutdown.
- Belts and couplings: Inspect for wear; replace per manufacturer interval.

Air treatment equipment:
- Refrigeration air dryer: Removes moisture by cooling air to a dewpoint of typically +3 to +7 °C. Drain the condensate separator daily. Inspect dryer outlet temperature and dewpoint monthly.
- Activated carbon filters: Remove hydrocarbon vapors and oil mist. Replace element every 6 months or per manufacturer recommendation.
- Point-of-use FRL units (filter-regulator-lubricator): Filter bowl drains daily; element replaced every 12 months. Lubricator is removed for painting and coating applications.

Compressed air leaks: Air leaks in the distribution system are a major energy waste (a 1 mm diameter leak at 7 bar wastes approximately 1.5 m³/hr of free air). Annual leak surveys using ultrasonic leak detectors identify and tag leaks for repair. Leak repair is prioritized by leak rate.
"""

version = "0.0.1"
