title = "Metal Scrap Segregation and Recycling Process"

content = """
Metal scrap is a significant material byproduct at Ridgecrest Metalworks, generated from cutting, stamping, turning, milling, grinding, and sawing operations. Properly segregated and managed scrap is a recyclable commodity with real economic value—mixed or contaminated scrap loses value dramatically and may create disposal compliance problems.

**Types of scrap generated.** Different manufacturing processes generate different scrap types:
- **Punch and laser skeleton scrap:** Sheet steel or aluminum remnants after blanking. Large, flat, relatively clean.
- **Turning chips and swarf:** Generated by lathe and mill operations. Loose, fine, mixed with cutting fluid.
- **Saw cutoffs and drops:** End pieces from bar stock and tube. Larger and easier to handle.
- **Grinding swarf:** Very fine metallic particles mixed with grinding fluid. May contain abrasive grit.
- **Weld spatter and slag:** Small irregular particles from MIG, TIG, and stick welding operations.

**Segregation requirements.** Scrap must be segregated by alloy family to maximize recycling value and avoid metallurgical contamination:
- Carbon steel (A36, 1018, A500 tube) — dedicated carbon steel scrap bin.
- Low alloy steel (4140, 4340) — dedicated alloy steel scrap bin (separate from carbon steel).
- Stainless steel (304, 316, 17-4) — dedicated stainless scrap bin. Stainless is a high-value recycle stream. Never mix with carbon steel.
- Aluminum (6061, 5052) — dedicated aluminum scrap bin.
- Mixed or unknown metal — a separate "contaminated" bin; this goes to a lower-value recycler.

**Scrap containers.** Each scrap bin is color-coded and labeled by alloy type. Full bins are collected by the warehouse team and weighed before pickup. Weight is recorded in the scrap log (ERP or manual log) for material balance tracking.

**Coolant-wetted chips.** Chips contaminated with cutting fluid must drain before disposal. Chip wringers are available at the lathe and mill centers. Adequately drained chips are classified as non-hazardous scrap metal. Chips with free-flowing liquid are a different waste stream requiring separate handling.

**Recycling contractor.** Ridgecrest's approved scrap recycler is on the approved vendor list. Scrap is picked up on a scheduled basis. The recycler provides scrap manifests showing weight by alloy type and dollar return. This revenue partially offsets raw material costs.

Contaminating scrap streams—throwing trash, wood, or other materials into metal scrap bins—is a disciplinary matter as it destroys recycling value and may create waste compliance issues.
"""

version = "0.0.1"
