title = "Scrap Classification and Internal Recycling"

content = """
Metal scrap generated during production at Ridgecrest Metalworks is a significant material stream
with both economic value and environmental management obligations. Proper classification, segregation,
and handling of scrap and swarf protects revenue from material recovery and maintains regulatory
compliance for waste metals.

Categories of Internal Scrap:

Chips and Swarf: Generated by all machining operations. Chip form (long stringy chips, short curls,
powder-like fines) varies by material and cutting parameters. Chips are collected in chip conveyors,
chip drums, and swarf bins at each machining center. Chips contain residual cutting fluid that must
be managed.

Cutoff Drops and Remnant Pieces: Short lengths of bar stock, plate offcuts, and other remnant pieces
that cannot be used for another production job. These are typically of known alloy identity and have
the highest recovery value.

Reject and Scrapped Parts: Components rejected at in-process or final inspection due to dimensional
non-conformance, surface defects, or material issues. These are placed on scrap disposition orders
before being released to the scrap stream.

Segregation Requirements:
Scrap must be segregated strictly by alloy family. Co-mingled scrap streams significantly reduce
recovery value and create liability if the mixed material is recycled without correct composition
labeling. Segregated scrap containers are labeled by material type:
- Carbon steel chips (separate bin)
- Stainless steel chips and drops
- Aluminum chips and drops
- Copper and brass chips and drops
- Specialty alloys (nickel, titanium): held separately, sold to specialty scrap processors

Coolant-Laden Chips:
Chips from the machining center contain significant quantities of cutting fluid. Before sale or disposal,
chips go through a centrifugal chip wringer or briquetter to remove coolant. Recovered coolant is
returned to the sump system or disposed of per the facility's waste cutting fluid management plan.
Coolant-contaminated chips cannot be placed in general scrap bins — they require proper waste handling.

Environmental Compliance:
Metal scrap sold to recyclers must be accompanied by a waste profile sheet or vendor certification
confirming it is non-hazardous under applicable regulations. Chips containing cutting fluid may be
classified as industrial waste if coolant content exceeds thresholds defined by state environmental
regulations. The EHS coordinator maintains the waste profiling records.
"""

version = "0.0.1"
