title = "E-Way Bill Basics"

content = """
The e-way bill is a mandatory electronic document for movement of goods in India above the
prescribed value threshold. Ganges Highway must ensure every consignment that qualifies
has a valid e-way bill before dispatch.

**When Required:** Movement of goods worth more than the notified limit (typically INR 50,000
for most goods) requires an e-way bill. Certain goods and scenarios have different rules;
check the GST portal for current thresholds and exemptions.

**Generation:** The e-way bill can be generated by the supplier, recipient, or the transporter.
As the operator, we often generate or update e-way bills on behalf of clients when we have
the invoice and consignment details. The document is linked to the vehicle number and valid
for a defined distance or time.

**Carriage:** A copy (electronic or printed) must be carried in the vehicle. At check-posts
and during inspections, authorities verify the e-way bill against the vehicle, goods, and
supporting documents. Mismatch or absence can lead to detention and penalty.
"""  # noqa: E501

version = "0.0.1"
